# 1. The exact connection route that worked in DBeaver
spring.datasource.url= #oracle database url
spring.datasource.username= #database username
spring.datasource.password= #databse password
server.port=8080
# 2. Tell Spring Boot we are using Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# 3. Tell Hibernate to automatically build your tables
spring.jpa.hibernate.ddl-auto= update

# 4. Show the SQL in the IntelliJ console so you can see it working
spring.jpa.show-sql=true
# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= #email you want to send the emails from
spring.mail.password= #app password for the mail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Allow larger file uploads (10MB is a safe standard for profile pictures)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
gif.provider = klipy
gif.klipy.api-key = #api key here
