package org.example.uptodate.controller;
import org.example.uptodate.model.User;
import org.example.uptodate.repository.UserRepository;
import org.example.uptodate.services.FileStorageService;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Controller
public class SetupController {
    private UserRepository userRepository;
    private FileStorageService fileStorageService;

    public SetupController(UserRepository userRepository, FileStorageService fileStorageService) {
        this.userRepository = userRepository;
        this.fileStorageService = fileStorageService;
    }

    @GetMapping("/setup")
    public String showSetupPage(Authentication authentication, Model model) {
        String currentUsername = authentication.getName();
        User user = userRepository.findByUsername(currentUsername).orElseThrow();
        if (user.isIfProfileSetUp()) {
            return "redirect:/feed";
        }
        model.addAttribute("user", user);
        return "setup";
    }
    @PostMapping("/setup")
    public String processSetup(
            Authentication authentication,
            @RequestParam("bio") String bio,
            @RequestParam("interests") List<String> interests,
            @RequestParam("profilePic") MultipartFile profilePic
    ) throws IOException {

        System.out.println("--- SETUP PROCESS STARTED ---");

        User user = userRepository.findByUsername(authentication.getName()).orElseThrow();
        System.out.println("1. User found: " + user.getUsername());

        user.setBio(bio);
        Map<String, Integer> initialWeights = new HashMap<>();
        if (interests != null) {
            for (String interest : interests) {
                initialWeights.put(interest.toLowerCase(), 100);
            }
        }
        user.setInterestWeights(initialWeights);

        System.out.println("2. Is profilePic empty? " + profilePic.isEmpty());

        // 2. Handle File Upload
        if (!profilePic.isEmpty()) {
            System.out.println("3. File received! Name: " + profilePic.getOriginalFilename() + ", Size: " + profilePic.getSize());

            String avatarUrl = fileStorageService.saveProfilePicture(profilePic);
            System.out.println("4. URL generated by FileStorageService: " + avatarUrl);

            user.setProfilePictureUrl(avatarUrl);
            System.out.println("5. URL set on User object: " + user.getProfilePictureUrl());
        }

        // 3. Mark setup as complete and save
        user.setIfProfileSetUp(true);
        userRepository.save(user);

        System.out.println("6. User saved to database!");
        System.out.println("--- SETUP PROCESS FINISHED ---");

        return "redirect:/feed";
    }
}
